version: '3.8'

services:
  server-gateway:
    image: 'aryunin/marr-server-gateway:dev'
    container_name: server-gateway
    environment:
      - MAIN_HOST=server-main
      - MAIN_PORT=8080
      - SURVEY_HOST=server-survey
      - SURVEY_PORT=8080
      - RCM_HOST=server-rcm
      - RCM_PORT=8080
      - API_PREFIX=/api
      - SERVICE_PORT=8080
      - LOG_LEVEL=INFO
    ports: 
      - 8081:8080
    restart: always
    networks:
      - front-net
      - server-net

  server-main:
    image: 'aryunin/marr-server-main:dev'
    container_name: server-main
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=statistigz
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVICE_PORT=8080
      - LOG_LEVEL=INFO
    restart: always
    networks:
      - server-net
    
#  server-survey:
#    image: 'myimg'
#    container_name: server-survey
#    depends_on: 
#      db:
#        condition: service_healthy
#    environment:
#      - DB_HOST=db
#      - DB_PORT=5432
#      - DB_NAME=statistigz
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#      - SERVICE_PORT=8080
#      - LOG_LEVEL=INFO
#    restart: always
#    networks:
#      - server-net
    
  server-rcm:
    image: 'aryunin/marr-server-rcm:dev'
    container_name: server-rcm
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=statistigz
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVICE_PORT=8080
      - CLASSIFIER_HOST=classifier
      - CLASSIFIER_PORT=8080
      - LOG_LEVEL=INFO
    restart: always
    networks:
      - server-net
    
  classifier:
    image: 'aryunin/marr-classifier:dev'
    container_name: classifier
    environment:
      - SERVICE_PORT=8080
    restart: always
    networks:
      - server-net
    
  excel-loader:
    image: 'aryunin/marr-excel-loader:dev'
    container_name: excel-loader
    environment:
      - HOST=db
      - PORT=5432
      - DB_NAME=statistigz
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/statistigz
      - PREV_SERVICE_HOST=server-main
      - PREV_SERVICE_PORT=8080
    networks:
      - server-net  

  db:
    image: 'postgres:16.0'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=statistigz
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 120s
      retries: 5
    networks:
      - server-net  
      
  front:
    image: 'aryunin/marr-front:dev'
    container_name: front
    environment:
      - API_HOST=server-gateway
      - API_PORT=8080
    ports: 
      - 8080:80
    restart: always
    networks:
      - front-net
      
volumes:
  pgdata:
  
networks:
  server-net:
    driver: bridge
  front-net:
    driver: bridge