version: '3.8'

services:
  excel-loader:
    image: 'aryunin/marr-uploader:dev'
    container_name: excel-loader
    depends_on:
      - server
    environment:
      - HOST=db
      - PORT=5432
      - DB_NAME=statistigz
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/statistigz
    entrypoint: su -c "./wait-for-it.sh -s -t 120 server:8080 -- python -u uploader.py"

  server:
    image: 'aryunin/marr-server:dev'
    entrypoint: su -c "java -jar application.jar"
    container_name: server
    depends_on: 
      db:
        condition: service_healthy 
    environment:
      - DB_HOST=db
      - DB_NAME=statistigz
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports: 
      - 8080:8080
    restart: always

  db:
    image: 'postgres:16.0'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=statistigz
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 120s
      retries: 5
      
volumes:
  pgdata:
    