CREATE TABLE Region (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    description text NOT NULL DEFAULT ''
);

CREATE TABLE Projection (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL
);

CREATE TABLE Criteria (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    projectionId bigint NOT NULL,
    FOREIGN KEY (projectionId) REFERENCES Projection(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE City_Criteria (
    regionId bigint REFERENCES Region(id) ON DELETE CASCADE ON UPDATE CASCADE,
    criteriaId bigint REFERENCES Criteria(id) ON DELETE CASCADE ON UPDATE CASCADE,
    "year" integer NOT NULL,
    "value" double precision NOT NULL,
    PRIMARY KEY(regionId, criteriaId, "year")
);