spring:
  main:
    banner-mode: off
  application:
    name: region-recommendation
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    schemas: region_recommendation
  webflux:
    base-path: ${SERVICE_PATH}

server:
  port: ${SERVICE_PORT}

service:
  classifier:
    host: ${CLASSIFIER_HOST}
    port: ${CLASSIFIER_PORT}
    path: ${CLASSIFIER_PATH}
    protocol: http

logging:
  level:
    org.springframework: ${LOG_LEVEL}
    com.statistigz.rcm: ${LOG_LEVEL}