version: '3.8'

services:
  uploader:
    image: 'uploader:latest'
    build:
      context: ../excel_uploader
    container_name: uploader
    depends_on:
      - api

  api:
    image: 'main:latest'
    build:
      context: ./main
    container_name: main
    depends_on: 
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=statistigz
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports: 
      - 8080:8080
    restart: always

  db:
    image: 'postgres:latest'
    build:
      context: ./db
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=statistigz
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
    