version: '3.8'

services:
  uploader:
    image: 'uploader:latest'
    build:
      context: ../excel_uploader
    container_name: uploader
    depends_on:
      - api
    entrypoint: su -c "./wait-for-it.sh api:8080 -- python -u uploader.py"

  api:
    image: 'main:latest'
    build:
      context: ./main
    entrypoint: su -c "java -jar application.jar"
    container_name: main
    depends_on: 
      db:
        condition: service_healthy 
    environment:
      - DB_HOST=db
      - DB_NAME=statistigz
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports: 
      - 8080:8080
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: 'postgres:16.0'
    build:
      context: ./db
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=statistigz
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  pgdata:
    