CREATE TABLE IF NOT EXISTS Region (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    description text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Projection (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Criteria (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    projection_id bigint NOT NULL,
    FOREIGN KEY (projection_id) REFERENCES Projection(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Region_Photo (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    region_id bigint REFERENCES Region(id) ON DELETE CASCADE ON UPDATE CASCADE,
    order_idx int NOT NULL CHECK(order_idx >= 0),
    data bytea NOT NULL
);

CREATE TABLE IF NOT EXISTS Region_Criteria (
    region_id bigint REFERENCES Region(id) ON DELETE CASCADE ON UPDATE CASCADE,
    criteria_id bigint REFERENCES Criteria(id) ON DELETE CASCADE ON UPDATE CASCADE,
    update_year int NOT NULL,
    "value" double precision NOT NULL,
    PRIMARY KEY(region_id, criteria_id, update_year)
);