-- Таблички

CREATE TABLE IF NOT EXISTS region (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    description text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS projection (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS criteria (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    projection_id bigint NOT NULL,
    FOREIGN KEY (projection_id) REFERENCES projection(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS region_photo (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    region_id bigint REFERENCES region(id) ON DELETE CASCADE ON UPDATE CASCADE,
    data bytea NOT NULL
);
CREATE INDEX region_photo_region_id_idx ON region_photo(region_id);

CREATE TABLE IF NOT EXISTS region_criteria (
    region_id bigint REFERENCES region(id) ON DELETE CASCADE ON UPDATE CASCADE,
    criteria_id bigint REFERENCES criteria(id) ON DELETE CASCADE ON UPDATE CASCADE,
    update_year int NOT NULL,
    "value" double precision NOT NULL,
    PRIMARY KEY(region_id, criteria_id, update_year)
);

-- Проекции

INSERT INTO projection(name) VALUES ('Экономика');
INSERT INTO projection(name) VALUES ('Образование');
INSERT INTO projection(name) VALUES ('Труд и занятость');
INSERT INTO projection(name) VALUES ('Семья');
INSERT INTO projection(name) VALUES ('Уровень жизни');
INSERT INTO projection(name) VALUES ('Демография');
INSERT INTO projection(name) VALUES ('Экология');
INSERT INTO projection(name) VALUES ('Внешняя торговля');
INSERT INTO projection(name) VALUES ('Инвестиции');
INSERT INTO projection(name) VALUES ('Здравоохранение');
INSERT INTO projection(name) VALUES ('Транспорт');
INSERT INTO projection(name) VALUES ('Культура и досуг');
INSERT INTO projection(name) VALUES ('Финансы');
INSERT INTO projection(name) VALUES ('Инновации');
INSERT INTO projection(name) VALUES ('Торговля и услуги');
INSERT INTO projection(name) VALUES ('Жильё');
INSERT INTO projection(name) VALUES ('Общий критерий');

-- Критерии

INSERT INTO criteria(name, projection_id) VALUES('Объем продукции сельского хозяйства на душу населения', 1);
INSERT INTO criteria(name, projection_id) VALUES('Объем строительства на душу населения', 1);
INSERT INTO criteria(name, projection_id) VALUES('Объем продукции обрабатывающего производства на душу населения', 1);
INSERT INTO criteria(name, projection_id) VALUES('Охват дошкольным образованием', 2);
INSERT INTO criteria(name, projection_id) VALUES('Число студентов организаций среднего специального образования на 10000 населения', 2);
INSERT INTO criteria(name, projection_id) VALUES('Число студентов организаций высшего образования на 10000 населения', 2);
INSERT INTO criteria(name, projection_id) VALUES('Уровень безработицы', 3);
INSERT INTO criteria(name, projection_id) VALUES('Среднемесячная номинальная заработная плата', 3);
INSERT INTO criteria(name, projection_id) VALUES('Численность занятых на одного пенсионера', 3);
INSERT INTO criteria(name, projection_id) VALUES('Число разводов на 1000 браков', 4);
INSERT INTO criteria(name, projection_id) VALUES('Суммарный коэффициент рождаемости', 4);
INSERT INTO criteria(name, projection_id) VALUES('Ввод в действие дошкольных организаций на душу населения', 4);
INSERT INTO criteria(name, projection_id) VALUES('Отношение среднедушевых доходов к прожиточному минимуму', 5);
INSERT INTO criteria(name, projection_id) VALUES('Доля населения с доходами ниже величины прожиточного минимума', 5);
INSERT INTO criteria(name, projection_id) VALUES('Коэффициент фондов', 5);
INSERT INTO criteria(name, projection_id) VALUES('Коэффициент естественного прироста населения', 6);
INSERT INTO criteria(name, projection_id) VALUES('Ожидаемая продолжительность жизни при рождении', 6);
INSERT INTO criteria(name, projection_id) VALUES('Коэффициент миграционного прироста населения', 6);
INSERT INTO criteria(name, projection_id) VALUES('Лесовосстановление', 7);
INSERT INTO criteria(name, projection_id) VALUES('Сброс загрязненных сточных вод', 7);
INSERT INTO criteria(name, projection_id) VALUES('Выбросы загрязняющих веществ от стационарных источников', 7);
INSERT INTO criteria(name, projection_id) VALUES('Экспорт', 8);
INSERT INTO criteria(name, projection_id) VALUES('Импорт', 8);
INSERT INTO criteria(name, projection_id) VALUES('Экспорт технологий и услуг технологического характера', 8);
INSERT INTO criteria(name, projection_id) VALUES('Степень износа основных фондов', 9);
INSERT INTO criteria(name, projection_id) VALUES('Инвестиции в основные фонды в % от ВРП', 9);
INSERT INTO criteria(name, projection_id) VALUES('Поступление прямых иностранных инвестиций', 9);
INSERT INTO criteria(name, projection_id) VALUES('Численность врачей на 1000 человек', 10);
INSERT INTO criteria(name, projection_id) VALUES('Число больничных коек на 10000 чел. населения', 10);
INSERT INTO criteria(name, projection_id) VALUES('Заболеваемость на 1000 чел. населения', 10);
INSERT INTO criteria(name, projection_id) VALUES('Плотность автомобильных дорог общего пользования с твердым покрытием на 1000 км2 территории', 11);
INSERT INTO criteria(name, projection_id) VALUES('Число собственных легковых автомобилей на 1000 чел. населения', 11);
INSERT INTO criteria(name, projection_id) VALUES('Число дорожно-транспортных происшествий на 100000 населения', 11);
INSERT INTO criteria(name, projection_id) VALUES('Посещения театров и музеев на 1000 чел.', 12);
INSERT INTO criteria(name, projection_id) VALUES('Общее количество плавательных бассейнов на 1000 чел.', 12);
INSERT INTO criteria(name, projection_id) VALUES('Число туров по России на 1000 чел.', 12);
INSERT INTO criteria(name, projection_id) VALUES('Налоговые поступления в % к ВРП', 13);
INSERT INTO criteria(name, projection_id) VALUES('Объем жилищных кредитов на душу населения', 13);
INSERT INTO criteria(name, projection_id) VALUES('Вклады юридических и физических лиц на душу населения', 13);
INSERT INTO criteria(name, projection_id) VALUES('Инновационная активность', 14);
INSERT INTO criteria(name, projection_id) VALUES('Интенсивность затрат на инновационную деятельность', 14);
INSERT INTO criteria(name, projection_id) VALUES('Доля инновационной продукции в общем объеме отгруженной продукции', 14);
INSERT INTO criteria(name, projection_id) VALUES('Оборот розничной торговли на душу населения', 15);
INSERT INTO criteria(name, projection_id) VALUES('Оборот общественного питания на душу населения', 15);
INSERT INTO criteria(name, projection_id) VALUES('Объем платных услуг на душу населения', 15);
INSERT INTO criteria(name, projection_id) VALUES('Ввод в действие жилых домов на душу населения', 16);
INSERT INTO criteria(name, projection_id) VALUES('Площадь жилья на одного жителя', 16);
INSERT INTO criteria(name, projection_id) VALUES('Удельный вес расходов на ЖКХ в общей сумме потребительских расходов', 16);
INSERT INTO criteria(name, projection_id) VALUES('Общий критерий', 17);

-- Регионы

INSERT INTO region(name) VALUES('Белгородская область');
INSERT INTO region(name) VALUES('Брянская область');
INSERT INTO region(name) VALUES('Владимировская область');
INSERT INTO region(name) VALUES('Воронежская область');
INSERT INTO region(name) VALUES('Ивановская область');
INSERT INTO region(name) VALUES('Калужская область');
INSERT INTO region(name) VALUES('Костромская область');
INSERT INTO region(name) VALUES('Курская область');
INSERT INTO region(name) VALUES('Липецкая область');
INSERT INTO region(name) VALUES('Московская область');
INSERT INTO region(name) VALUES('Орловская область');
INSERT INTO region(name) VALUES('Рязанская область');
INSERT INTO region(name) VALUES('Смоленская область');
INSERT INTO region(name) VALUES('Тамбовская область');
INSERT INTO region(name) VALUES('Тверская область');
INSERT INTO region(name) VALUES('Тульская область');
INSERT INTO region(name) VALUES('Ярославская область');
INSERT INTO region(name) VALUES('г. Москва');
INSERT INTO region(name) VALUES('Республика Карелия ');
INSERT INTO region(name) VALUES('Республика Коми');
INSERT INTO region(name) VALUES('Архангельская область');
INSERT INTO region(name) VALUES('Вологодская область');
INSERT INTO region(name) VALUES('Калининградская область');
INSERT INTO region(name) VALUES('Ленинградская область');
INSERT INTO region(name) VALUES('Мурманская область');
INSERT INTO region(name) VALUES('Новгородская область');
INSERT INTO region(name) VALUES('Псковская область');
INSERT INTO region(name) VALUES('г. Санкт-Петербург');
INSERT INTO region(name) VALUES('Республика Адыгея');
INSERT INTO region(name) VALUES('Республика Калмыкия');
INSERT INTO region(name) VALUES('Республика Крым');
INSERT INTO region(name) VALUES('Краснодарский край');
INSERT INTO region(name) VALUES('Астраханская область');
INSERT INTO region(name) VALUES('Волгоградская область');
INSERT INTO region(name) VALUES('Ростовская область');
INSERT INTO region(name) VALUES('г. Севастополь');
INSERT INTO region(name) VALUES('Республика Дагестан');
INSERT INTO region(name) VALUES('Республика Ингушетия');
INSERT INTO region(name) VALUES('Кабардино-Балкария');
INSERT INTO region(name) VALUES('Карачаево-Черкесская Республика');
INSERT INTO region(name) VALUES('Республика Северная Осетия Алания');
INSERT INTO region(name) VALUES('Чеченская Республика');
INSERT INTO region(name) VALUES('Ставропольский край');
INSERT INTO region(name) VALUES('Республика Башкортостан');
INSERT INTO region(name) VALUES('Республика Марий Эл');
INSERT INTO region(name) VALUES('Республика Мордовия');
INSERT INTO region(name) VALUES('Республика Татарстан');
INSERT INTO region(name) VALUES('Удмуртская республика');
INSERT INTO region(name) VALUES('Чувашская республика');
INSERT INTO region(name) VALUES('Пермский край');
INSERT INTO region(name) VALUES('Кировская область');
INSERT INTO region(name) VALUES('Нижегородская область');
INSERT INTO region(name) VALUES('Оренбургская область');
INSERT INTO region(name) VALUES('Пензенская область');
INSERT INTO region(name) VALUES('Самарская область');
INSERT INTO region(name) VALUES('Саратовская область');
INSERT INTO region(name) VALUES('Ульяновская область');
INSERT INTO region(name) VALUES('Курганская область');
INSERT INTO region(name) VALUES('Свердловская область');
INSERT INTO region(name) VALUES('Тюменская область');
INSERT INTO region(name) VALUES('Челябинская область');
INSERT INTO region(name) VALUES('Республика Алтай');
INSERT INTO region(name) VALUES('Республика Бурятия');
INSERT INTO region(name) VALUES('Республика Тыва');
INSERT INTO region(name) VALUES('Республика Хакасия');
INSERT INTO region(name) VALUES('Алтайский край');
INSERT INTO region(name) VALUES('Забайкальский край');
INSERT INTO region(name) VALUES('Красноярский край');
INSERT INTO region(name) VALUES('Иркутская область');
INSERT INTO region(name) VALUES('Кемеровская область');
INSERT INTO region(name) VALUES('Новосибирская область');
INSERT INTO region(name) VALUES('Омская область');
INSERT INTO region(name) VALUES('Томская область');
INSERT INTO region(name) VALUES('Республика Саха (Якутия)');
INSERT INTO region(name) VALUES('Камчатский край');
INSERT INTO region(name) VALUES('Приморский край');
INSERT INTO region(name) VALUES('Хабаровский край');
INSERT INTO region(name) VALUES('Амурская область');
INSERT INTO region(name) VALUES('Магаданская область');
INSERT INTO region(name) VALUES('Сахалинская область');
INSERT INTO region(name) VALUES('Еврейская АО');
INSERT INTO region(name) VALUES('Чукотский АО');

-- Вьюхи

CREATE MATERIALIZED VIEW IF NOT EXISTS region_projection AS
WITH CTE AS (
	SELECT
		region_id,
		projection_id,
		update_year,
		score,
	MIN(score) OVER (PARTITION BY projection_id, update_year) AS xmin,
	MAX(score) OVER (PARTITION BY projection_id, update_year) AS xmax
	FROM (
        SELECT
            rc.region_id AS region_id,
            pr.id AS projection_id,
            rc.update_year AS update_year,
        AVG(rc."value") AS score
        FROM region_criteria rc
        JOIN criteria cr
            ON cr.id = rc.criteria_id
        JOIN projection pr
            ON pr.id = cr.projection_id
        GROUP BY rc.region_id, pr.id, update_year
	) AS CTE2
)
SELECT
	region_id,
	projection_id,
	update_year,
	(score - xmin) / (xmax - xmin) AS score,
	RANK() OVER (PARTITION BY projection_id, update_year ORDER BY score DESC) AS place
FROM CTE;
CREATE UNIQUE INDEX region_projection_region_id_projection_id_update_year_idx ON region_projection(region_id, projection_id, update_year);

CREATE MATERIALIZED VIEW IF NOT EXISTS achievement AS
WITH CTE AS (
    SELECT
        rp.region_id AS region_id,
        rp.projection_id AS projection_id,
        rp.update_year AS update_year,
		rp.score AS score,
        RANK() OVER (PARTITION BY rp.projection_id, rp.update_year ORDER BY rp.score DESC) AS rnk
    FROM region_projection rp
)
SELECT region_id, projection_id, update_year, score
FROM CTE
WHERE rnk = 1;
CREATE UNIQUE INDEX achievement_region_id_projection_id_update_year_idx ON achievement(region_id, projection_id, update_year);

-- Процедуры

CREATE PROCEDURE calculate_common_score() AS $$
    INSERT INTO Region_Criteria(region_id, criteria_id, update_year, "value")
		SELECT
		region_id,
		49,
		update_year,
		AVG("value") AS "value"
		FROM region_criteria
		GROUP BY region_id, update_year
		ON CONFLICT (region_id, criteria_id, update_year) DO UPDATE
		SET "value" = EXCLUDED."value"
$$ LANGUAGE SQL;

CREATE PROCEDURE refresh_all() AS $$
	CALL calculate_common_score();
    REFRESH MATERIALIZED VIEW CONCURRENTLY region_projection;
	REFRESH MATERIALIZED VIEW CONCURRENTLY achievement;
$$ LANGUAGE SQL;