-- Проекции

INSERT INTO Projection(name) VALUES ('Экономика');
INSERT INTO Projection(name) VALUES ('Образование');
INSERT INTO Projection(name) VALUES ('Труд и занятость');
INSERT INTO Projection(name) VALUES ('Семья');
INSERT INTO Projection(name) VALUES ('Уровень жизни');
INSERT INTO Projection(name) VALUES ('Демография');
INSERT INTO Projection(name) VALUES ('Экология');
INSERT INTO Projection(name) VALUES ('Внешняя торговля');
INSERT INTO Projection(name) VALUES ('Инвестиции');
INSERT INTO Projection(name) VALUES ('Здравоохранение');
INSERT INTO Projection(name) VALUES ('Транспорт');
INSERT INTO Projection(name) VALUES ('Культура и досуг');
INSERT INTO Projection(name) VALUES ('Финансы');
INSERT INTO Projection(name) VALUES ('Инновации');
INSERT INTO Projection(name) VALUES ('Торговля и услуги');
INSERT INTO Projection(name) VALUES ('Жильё');

-- Критерии

INSERT INTO Criteria(name, projection_id) VALUES('Объем продукции сельского хозяйства на душу населения', 1);
INSERT INTO Criteria(name, projection_id) VALUES('Объем строительства на душу населения', 1);
INSERT INTO Criteria(name, projection_id) VALUES('Объем продукции обрабатывающего производства на душу населения', 1);
INSERT INTO Criteria(name, projection_id) VALUES('Охват дошкольным образованием', 2);
INSERT INTO Criteria(name, projection_id) VALUES('Число студентов организаций среднего специального образования на 10000 населения', 2);
INSERT INTO Criteria(name, projection_id) VALUES('Число студентов организаций высшего образования на 10000 населения', 2);
INSERT INTO Criteria(name, projection_id) VALUES('Уровень безработицы', 3);
INSERT INTO Criteria(name, projection_id) VALUES('Среднемесячная номинальная заработная плата', 3);
INSERT INTO Criteria(name, projection_id) VALUES('Численность занятых на одного пенсионера', 3);
INSERT INTO Criteria(name, projection_id) VALUES('Число разводов на 1000 браков', 4);
INSERT INTO Criteria(name, projection_id) VALUES('Суммарный коэффициент рождаемости', 4);
INSERT INTO Criteria(name, projection_id) VALUES('Ввод в действие дошкольных организаций на душу населения', 4);
INSERT INTO Criteria(name, projection_id) VALUES('Отношение среднедушевых доходов к прожиточному минимуму', 5);
INSERT INTO Criteria(name, projection_id) VALUES('Доля населения с доходами ниже величины прожиточного минимума', 5);
INSERT INTO Criteria(name, projection_id) VALUES('Коэффициент фондов', 5);
INSERT INTO Criteria(name, projection_id) VALUES('Коэффициент естественного прироста населения', 6);
INSERT INTO Criteria(name, projection_id) VALUES('Ожидаемая продолжительность жизни при рождении', 6);
INSERT INTO Criteria(name, projection_id) VALUES('Коэффициент миграционного прироста населения', 6);
INSERT INTO Criteria(name, projection_id) VALUES('Лесовосстановление', 7);
INSERT INTO Criteria(name, projection_id) VALUES('Сброс загрязненных сточных вод', 7);
INSERT INTO Criteria(name, projection_id) VALUES('Выбросы загрязняющих веществ от стационарных источников', 7);
INSERT INTO Criteria(name, projection_id) VALUES('Экспорт', 8);
INSERT INTO Criteria(name, projection_id) VALUES('Импорт', 8);
INSERT INTO Criteria(name, projection_id) VALUES('Экспорт технологий и услуг технологического характера', 8);
INSERT INTO Criteria(name, projection_id) VALUES('Степень износа основных фондов', 9);
INSERT INTO Criteria(name, projection_id) VALUES('Инвестиции в основные фонды в % от ВРП', 9);
INSERT INTO Criteria(name, projection_id) VALUES('Поступление прямых иностранных инвестиций', 9);
INSERT INTO Criteria(name, projection_id) VALUES('Численность врачей на 1000 человек', 10);
INSERT INTO Criteria(name, projection_id) VALUES('Число больничных коек на 10000 чел. населения', 10);
INSERT INTO Criteria(name, projection_id) VALUES('Заболеваемость на 1000 чел. населения', 10);
INSERT INTO Criteria(name, projection_id) VALUES('Плотность автомобильных дорог общего пользования с твердым покрытием на 1000 км2 территории', 11);
INSERT INTO Criteria(name, projection_id) VALUES('Число собственных легковых автомобилей на 1000 чел. населения', 11);
INSERT INTO Criteria(name, projection_id) VALUES('Число дорожно-транспортных происшествий на 100000 населения', 11);
INSERT INTO Criteria(name, projection_id) VALUES('Посещения театров и музеев на 1000 чел.', 12);
INSERT INTO Criteria(name, projection_id) VALUES('Общее количество плавательных бассейнов на 1000 чел.', 12);
INSERT INTO Criteria(name, projection_id) VALUES('Общее количество плавательных бассейнов на 1000 чел.', 12);
INSERT INTO Criteria(name, projection_id) VALUES('Налоговые поступления в % к ВРП', 13);
INSERT INTO Criteria(name, projection_id) VALUES('Объем жилищных кредитов на душу населения', 13);
INSERT INTO Criteria(name, projection_id) VALUES('Вклады юридических и физических лиц на душу населения', 13);
INSERT INTO Criteria(name, projection_id) VALUES('Инновационная активность', 14);
INSERT INTO Criteria(name, projection_id) VALUES('Интенсивность затрат на инновационную деятельность', 14);
INSERT INTO Criteria(name, projection_id) VALUES('Доля инновационной продукции в общем объеме отгруженной продукции', 14);
INSERT INTO Criteria(name, projection_id) VALUES('Оборот розничной торговли на душу населения', 15);
INSERT INTO Criteria(name, projection_id) VALUES('Оборот общественного питания на душу населения', 15);
INSERT INTO Criteria(name, projection_id) VALUES('Объем платных услуг на душу населения', 15);
INSERT INTO Criteria(name, projection_id) VALUES('Ввод в действие жилых домов на душу населения', 16);
INSERT INTO Criteria(name, projection_id) VALUES('Площадь жилья на одного жителя', 16);
INSERT INTO Criteria(name, projection_id) VALUES('Удельный вес расходов на ЖКХ в общей сумме потребительских расходов', 16);

-- Регионы

INSERT INTO Region(name) VALUES('г. Москва');
INSERT INTO Region(name) VALUES('г. Санкт-Петербург');
INSERT INTO Region(name) VALUES('Республика Татарстан');
INSERT INTO Region(name) VALUES('Калужская область');
INSERT INTO Region(name) VALUES('Сахалинская область');
INSERT INTO Region(name) VALUES('Московская область');
INSERT INTO Region(name) VALUES('Тюменская область');
INSERT INTO Region(name) VALUES('Нижегородская область');
INSERT INTO Region(name) VALUES('Калининградская область');
INSERT INTO Region(name) VALUES('Вологодская область');
INSERT INTO Region(name) VALUES('Камчатский край');
INSERT INTO Region(name) VALUES('Чукотский АО');
INSERT INTO Region(name) VALUES('Ленинградская область');
INSERT INTO Region(name) VALUES('Хабаровский край');
INSERT INTO Region(name) VALUES('Свердловская область');
INSERT INTO Region(name) VALUES('Липецкая область');
INSERT INTO Region(name) VALUES('Тульская область');
INSERT INTO Region(name) VALUES('Самарская область');
INSERT INTO Region(name) VALUES('Республика Саха (Якутия)');
INSERT INTO Region(name) VALUES('Ростовская область');
INSERT INTO Region(name) VALUES('Новосибирская область');
INSERT INTO Region(name) VALUES('Красноярский край');
INSERT INTO Region(name) VALUES('Ярославская область');
INSERT INTO Region(name) VALUES('Краснодарский край');
INSERT INTO Region(name) VALUES('Магаданская область');
INSERT INTO Region(name) VALUES('Тверская область');
INSERT INTO Region(name) VALUES('Пермский край');
INSERT INTO Region(name) VALUES('Белгородская область');
INSERT INTO Region(name) VALUES('Томская область');
INSERT INTO Region(name) VALUES('Новгородская область');
INSERT INTO Region(name) VALUES('Воронежская область');
INSERT INTO Region(name) VALUES('Архангельская область');
INSERT INTO Region(name) VALUES('Псковская область');
INSERT INTO Region(name) VALUES('Республика Карелия ');
INSERT INTO Region(name) VALUES('Омская область');
INSERT INTO Region(name) VALUES('Республика Мордовия');
INSERT INTO Region(name) VALUES('Костромская область');
INSERT INTO Region(name) VALUES('Иркутская область');
INSERT INTO Region(name) VALUES('Ульяновская область');
INSERT INTO Region(name) VALUES('Владимировская область');
INSERT INTO Region(name) VALUES('Смоленская область');
INSERT INTO Region(name) VALUES('Рязанская область');
INSERT INTO Region(name) VALUES('Республика Башкортостан');
INSERT INTO Region(name) VALUES('Мурманская область');
INSERT INTO Region(name) VALUES('Челябинская область');
INSERT INTO Region(name) VALUES('Курская область');
INSERT INTO Region(name) VALUES('Кировская область');
INSERT INTO Region(name) VALUES('Волгоградская область');
INSERT INTO Region(name) VALUES('Пензенская область');
INSERT INTO Region(name) VALUES('г. Севастополь');
INSERT INTO Region(name) VALUES('Республика Крым');
INSERT INTO Region(name) VALUES('Брянская область');
INSERT INTO Region(name) VALUES('Тамбовская область');
INSERT INTO Region(name) VALUES('Удмуртская республика');
INSERT INTO Region(name) VALUES('Приморский край');
INSERT INTO Region(name) VALUES('Республика Коми');
INSERT INTO Region(name) VALUES('Алтайский край');
INSERT INTO Region(name) VALUES('Чувашская республика');
INSERT INTO Region(name) VALUES('Амурская область');
INSERT INTO Region(name) VALUES('Республика Бурятия');
INSERT INTO Region(name) VALUES('Орловская область');
INSERT INTO Region(name) VALUES('Ставропольский край');
INSERT INTO Region(name) VALUES('Кемеровская область');
INSERT INTO Region(name) VALUES('Республика Алтай');
INSERT INTO Region(name) VALUES('Ивановская область');
INSERT INTO Region(name) VALUES('Саратовская область');
INSERT INTO Region(name) VALUES('Оренбургская область');
INSERT INTO Region(name) VALUES('Республика Марий Эл');
INSERT INTO Region(name) VALUES('Республика Хакасия');
INSERT INTO Region(name) VALUES('Астраханская область');
INSERT INTO Region(name) VALUES('Курганская область');
INSERT INTO Region(name) VALUES('Кабардино-Балкария');
INSERT INTO Region(name) VALUES('Забайкальский край');
INSERT INTO Region(name) VALUES('Республика Тыва');
INSERT INTO Region(name) VALUES('Чеченская Республика');
INSERT INTO Region(name) VALUES('Республика Адыгея');
INSERT INTO Region(name) VALUES('Республика Дагестан');
INSERT INTO Region(name) VALUES('Еврейская АО');
INSERT INTO Region(name) VALUES('Республика Северная Осетия Алания');
INSERT INTO Region(name) VALUES('Республика Ингушетия');
INSERT INTO Region(name) VALUES('Республика Калмыкия');
INSERT INTO Region(name) VALUES('Карачаево-Черкесская Республика');