spring:
  main:
    banner-mode: off
  application:
    name: gateway
  cloud:
    gateway:
      global-filter:
        local-response-cache:
          enabled: true
      filter:
        local-response-cache:
          enabled: true
          size: 500MB
          time-to-live: 30m
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGIN}
            allowedMethods:
              - GET
              - POST
            allowedHeaders: '*'
      routes:
        #        - id: survey
        #          uri: http://${SURVEY_HOST}:${SURVEY_PORT}
        #          predicates:
        #            - Path=${API_PREFIX}/survey/**
        #          filters:
        #            - StripPrefix=2
        #            - LocalResponseCache=30m,500MB
        - id: rcm
          uri: http://${RCM_HOST}:${RCM_PORT}
          predicates:
            - Path=${API_PREFIX}/rcm/**
          filters:
            - StripPrefix=2
        - id: main
          uri: http://${MAIN_HOST}:${MAIN_PORT}
          predicates:
            - Path=${API_PREFIX}/**
          filters:
            - StripPrefix=1

server:
  port: ${SERVICE_PORT}
logging:
  level:
    org.springframework: ${LOG_LEVEL}
    com.statistigz.gateway: ${LOG_LEVEL}