spring:
  main:
    banner-mode: off
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
            allowedHeaders: '*'
      routes:
        - id: rcm
          uri: http://${RCM_HOST}:${RCM_PORT}
          predicates:
            - Path=${API_PREFIX}/rcm/**
          filters:
            - StripPrefix=2
        - id: main
          uri: http://${MAIN_HOST}:${MAIN_PORT}
          predicates:
            - Path=${API_PREFIX}/**
          filters:
            - StripPrefix=1

server:
  port: ${SERVICE_PORT}
logging:
  level:
    org.springframework: ${LOG_LEVEL}
    com.statistigz.gateway: ${LOG_LEVEL}
