name: build & push
on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: calver      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        working-directory: ${{env.working-directory}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aryunin/marr-server
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{env.working-directory}}/main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Rename jar
        run: mv ./main/target/*.jar ./main/target/server-${{ steps.version.outputs.version }}.jar
        working-directory: ${{env.working-directory}}      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-${{ steps.version.outputs.version }}
          retention-days: 30
          compression-level: 0
          path: ${{env.working-directory}}/main/target/*.jar
  excel-loader:
    runs-on: ubuntu-latest
    env:
      working-directory: ./excel-loader
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aryunin/marr-uploader
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{env.working-directory}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  front:
    runs-on: ubuntu-latest
    env:
      working-directory: ./web-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aryunin/marr-front
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{env.working-directory}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}       
  mobile-app:
    name: Build mobile application
    runs-on: ubuntu-latest
    env:
      working-directory: ./mobile-app
    steps: 
      - uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: calver      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: gradle
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.13.9'
      - name: Dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}}
      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
        working-directory: ${{env.working-directory}}
      # - name: Test
      #   run: flutter test
        # working-directory: ${{env.working-directory}}
      - name: Build apk
        run: flutter build apk
        working-directory: ${{env.working-directory}}
      # - name: Build appbundle
      #   run: flutter build appbundle
      #   working-directory: ${{env.working-directory}}
      - name: Rename apk
        run: mv ./build/app/outputs/apk/release/app-release.apk ./build/app/outputs/apk/release/app-${{ steps.version.outputs.version }}.apk
        working-directory: ${{env.working-directory}}        
      - name: Upload artifacts   
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ steps.version.outputs.version }}
          retention-days: 30
          compression-level: 0
          path: ${{env.working-directory}}/build/app/outputs/apk/release/app-${{ steps.version.outputs.version }}.apk
