name: build & push
on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package
        working-directory: ${{env.working-directory}}
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: calver
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aryunin/marr-server
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{env.working-directory}}/main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Rename jar
        run: mv ${{env.working-directory}}/main/target/*.jar ${{env.working-directory}}/main/target/server-${{steps.version.outputs.version}}.jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-${{steps.version.outputs.version}}
          retention-days: 30
          compression-level: 0
          path: ${{env.working-directory}}/main/target/*.jar
  excel-loader:
    runs-on: ubuntu-latest
    env:
      working-directory: ./excel-loader
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aryunin/marr-uploader
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{env.working-directory}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  front:
    runs-on: ubuntu-latest
    env:
      working-directory: ./web-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aryunin/marr-front
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{env.working-directory}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
