name: issue links
on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  issue-links:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          resolve: 'true'
          branch-prefix: /
