name: test build
on:
  pull_request:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        working-directory: ${{env.working-directory}}
